version: '3'
services:
  php:
    container_name: "php"
    build: php-src
    volumes:
      - ./src/:/var/www/html/
      - ~/.ssh:/root/.ssh

  nginx:
    container_name: "nginx"
    build: nginx-src
    volumes:
      - ./src/:/var/www/html/
      - ./nginx-src/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - php

